import Navbar from "./navbar";
import Footer from "./footer";
import { FC, ReactNode } from "react";
import Head from "next/head";
import Header from "./header";

interface Props {
  children?: ReactNode;
}

const Layout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Personal Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
