import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { FC, ReactNode } from "react";
import Head from "next/head";
import Header from "../components/header";

export default function MainLayout({ children }) {
  return (
    <>
      <Head>
        <title>Personal Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <main>{children}</main>
      <hr />
      <Footer />
    </>
  );
}
